//
// UntitledView.h
// Generated by Core Animator version 1.0 on 2/20/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

@protocol GearAnimationDelegate <NSObject>

- (void)gearWasTapped;

@end

IB_DESIGNABLE
@interface UntitledView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;
@property (unsafe_unretained) id <GearAnimationDelegate> delegate;

// spinEnlarge
//- (void)addSpinEnlargeAnimation;
//- (void)addSpinEnlargeAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
//- (void)addSpinEnlargeAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
//- (void)addSpinEnlargeAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
//- (void)addSpinEnlargeAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
//- (void)removeSpinEnlargeAnimation;

// spinShrink
//- (void)addSpinShrinkAnimation;
- (void)addSpinShrinkAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
//- (void)addSpinShrinkAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
//- (void)addSpinShrinkAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
//- (void)addSpinShrinkAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
//- (void)removeSpinShrinkAnimation;

//- (void)removeAllAnimations;

@end